// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHhe1nMfolgHYQXrar2zRPOr4_AA7xREM',
    appId: '1:551134046178:web:73dacd173261b352e5fbbb',
    messagingSenderId: '551134046178',
    projectId: 'flutter-web-push-github',
    authDomain: 'flutter-web-push-github.firebaseapp.com',
    storageBucket: 'flutter-web-push-github.appspot.com',
    measurementId: 'G-CRFVC8SGED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC87p71J5WvF3rqqCZf0jetHLZE1A7E5u8',
    appId: '1:551134046178:android:d3da4e38f1151d38e5fbbb',
    messagingSenderId: '551134046178',
    projectId: 'flutter-web-push-github',
    storageBucket: 'flutter-web-push-github.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg6sii5Bo0hKNDt3nsnSEh2c9B5AgpSC4',
    appId: '1:551134046178:ios:f9f1d2defb1544b2e5fbbb',
    messagingSenderId: '551134046178',
    projectId: 'flutter-web-push-github',
    storageBucket: 'flutter-web-push-github.appspot.com',
    iosClientId: '551134046178-74e8e09qa6rr3uptr1inaavvi1ml4spk.apps.googleusercontent.com',
    iosBundleId: 'com.example.webpush',
  );
}
